config/routes.rb
Rails.application.routes.draw do
  resources :domains
  resources :marks, path: 'links'
  root to: 'domains#index'
  
  get '/l/:uid', to: 'marks#redirect', as: 'redirect_link'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  has_many :marks, dependent: :destroy 
end

app/models/mark.rb
class Mark < ApplicationRecord
  require 'uri'

  belongs_to :domain, required: false

  validates :url, url: true, presence: true
  validates :tag, presence: true

  before_create :assign_domain
  before_create :assign_uid

  def assign_domain
    domain_name = URI.parse(url.to_s).host
    domain = Domain.find_or_create_by(name: domain_name)
    self.domain_id = domain.id
  end

  def assign_uid
    self.uid = [*('a'..'z'),*('A'..'Z'),*('0'..'9')].shuffle[0,8].join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  def show
    collection = @domain.marks
    if params['search']
      search_for = "%#{params['search']}%"
      collection = collection.joins(:domain).where('domains.name LIKE ? OR marks.name LIKE ? OR marks.url LIKE ? OR marks.tag LIKE ?', search_for, search_for, search_for, search_for) 
    end 
    @marks = collection.page(params[:page]).per(30)
  end

  def new
    @domain = Domain.new
  end

  def edit
  end

  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(:name)
    end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]
  # GET /marks
  # GET /marks.json
  def index
    collection = Mark.all
    if params['search']
      search_for = "%#{params['search']}%"
      collection = collection.joins(:domain).where('domains.name LIKE ? OR marks.name LIKE ? OR marks.url LIKE ? OR marks.tag LIKE ?', search_for, search_for, search_for, search_for) 
    end 
    @marks = collection.page(params[:page]).per(30)
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  def redirect
    @mark = Mark.find_by(uid: params[:uid])
    redirect_to @mark.url
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mark_params
      params.require(:mark).permit(:name, :url, :tag, :domain_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    flash.map do |key, value|
      level_class = case key
                    when 'notice' then 'alert alert-info'
                    when 'success' then 'alert alert-success'
                    when 'error' then 'alert alert-danger'
                    when 'alert' then 'alert alert-warning'
                    end
      content_tag :div, class: level_class do
        [value, button_tag].join('').html_safe
      end
    end.join('').html_safe
  end

  def button_tag
    content_tag :button, class: 'close', 'data-dismiss' => 'alert', type: 'button' do
      [
        content_tag(:span, 'x', 'aria-hidden' => 'true'),
        content_tag(:span, 'Close', class: 'sr-only')
      ].join('').html_safe
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/domains/_form.html.erb
<%= form_with(model: domain, local: true) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
        <% domain.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/domains/_marks_in_domain.html.erb
<% @domain.marks.each do |mark| %>
  <tr>
    <td><%= mark.name %></td>
    <td><%= mark.domain.name if mark.domain %></td>
    <td><%= mark.url %></td>
    <td><%= mark.tag %></td>
    <td><%= link_to redirect_link_url(mark.uid), redirect_link_url(mark.uid) %></td>
    <td><%= link_to 'Zobacz więcej', mark %></td>
    <td><%= link_to 'Popraw', edit_mark_path(mark) %></td>
    <td><%= link_to 'Usuń', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<h1>Domeny</h1>

<table class="table table-hovered">
  <thead>
    <tr>
      <th>Nazwa domeny</th>
      <th>Ilość zakładek</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= domain.marks.count %></td>
        <td><%= link_to 'Zobacz więcej', domain %></td>
        <td><%= link_to 'Usuń', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p>
  <strong>Nazwa domeny:</strong>
  <%= @domain.name %>
</p>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">First</th>
        <th scope="col">Link:</th>
        <th scope="col">URL:</th>
        <th scope="col">Tagi:</th>
        <th scope="col" colspan=4>Krótki URL:</th>
      </tr>
    </thead>
    <tbody>
    <%= render(partial: 'marks_in_domain', collection: @domain.marks) %>
    </tbody>
  </table>


<%= link_to 'Wróć', domains_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Domeny', root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Domeny', root_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Zakładki', marks_path, class: 'nav-link'%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
          <input value='<%= params[:search] %>' name='search' class="form-control mr-sm-2" type="search" placeholder="Wyszukaj" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Wyszukaj</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container flash_message">
      <%= flash_message %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/marks/_form.html.erb
<%= form_with(model: mark, local: true) do |form| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
        <% mark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag, class: 'form-control' %>
  </div>

    <form class="actions">
      <button class="btn btn-outline-success my-2 my-sm-0 float-right" type="submit">Stwórz</button>
    </form>

  </form>
<% end %>

app/views/marks/_mark.html.erb
<tr>
  <td><%= mark.name %></td>
  <td><%= mark.domain.name if mark.domain %></td>
  <td><%= mark.url %></td>
  <td><%= mark.tag %></td>
  <td><%= link_to redirect_link_url(mark.uid), redirect_link_url(mark.uid) %></td>
  <td><%= link_to 'Zobacz więcej', mark %></td>
  <td><%= link_to 'Popraw', edit_mark_path(mark) %></td>
  <td><%= link_to 'Usuń', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<div class="button-link">
  <%= link_to 'Nowa Zakładka', new_mark_path, :class=> "btn float-right btn-outline-success btn-newmark" %>
</div>

<div class="title-marks">
  <h1>Zakładki</h1>
</div>
<div id="content">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">First</th>
        <th scope="col">Link:</th>
        <th scope="col">URL:</th>
        <th scope="col">Tagi:</th>
        <th scope="col" colspan=4>Krótki URL:</th>
      </tr>
    </thead>
    <tbody>
    <%= render(partial: 'mark', collection: @marks) %>
    </tbody>
  </table>

<% unless @marks.current_page == @marks.total_pages %>
  <p id="view-more">
    <%= link_to('Zaladuj wiecej', url_for(page: @marks.current_page + 1), remote: true) %>
  </p>
<% end %>

app/views/marks/index.js.erb
$('#content table tbody').append("<%=j render(partial: 'mark', collection: @marks, format: 'html') %>");

<% if @marks.current_page == @marks.total_pages %>
  $('#view-more').remove();
<% else %>
  $('#view-more a').attr('href', '<%= url_for(page: @marks.current_page + 1) %>');
<% end %>

app/views/marks/new.html.erb
<h1>Nowa zakładka</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p>
  <strong>Nazwa:</strong>
  <%= @mark.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @mark.name, @mark.url, target: "_blank" %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @mark.tag %>
</p>

<p>
  <strong>Domena:</strong>
  <% if @mark.domain %>
  <%= link_to @mark.domain.name, domain_path(@mark.domain) %>
  <% else %>
    <%= @mark.domain_id %>
  <% end %>
</p>

<%= link_to 'Zmień', edit_mark_path(@mark) %> |
<%= link_to '<- Powrót', marks_path %>